In [33]:
import pandas as pd 
import json

##### 本檔案為整理不同的訓練方式在做交叉驗證的MAE比較結果彙整

In [62]:
model_folder_name = "train_use_full_data_update_weather_data"  
with open(f"./model_each_location/{model_folder_name}/d.json", "r", encoding="utf-8") as file:
    mae_data = json.load(file)

In [63]:
df1 = pd.json_normalize(mae_data,sep="-").transpose().reset_index(drop=False)
df1.columns = ["模型","MAE"]
df1["類別"] = "異地同時"
df1["模型"] = df1["模型"].str.split("-")
df1["模型"] = df1["模型"].str[1]
df1["裝置"] = df1["模型"].str.slice(start=3, stop=5)
df1

            模型         MAE    類別  裝置
0    02_01.pkl  157.291595  異地同時  01
1    02_03.pkl  148.949403  異地同時  03
2    02_04.pkl  178.388029  異地同時  04
3    02_05.pkl  236.925199  異地同時  05
4    02_06.pkl  164.897480  異地同時  06
..         ...         ...   ...  ..
267  01_13.pkl  313.454211  異地同時  13
268  01_14.pkl  311.548764  異地同時  14
269  01_15.pkl  594.145821  異地同時  15
270  01_16.pkl  566.789863  異地同時  16
271  01_17.pkl  603.461460  異地同時  17

[272 rows x 4 columns]

In [64]:
model_folder_name = "train_use_full_data_update_weather_datasingle_location"  
with open(f"./model_each_location/{model_folder_name}/d.json", "r", encoding="utf-8") as file:
    mae_data = json.load(file)

In [65]:
df2 = pd.json_normalize(mae_data).transpose().reset_index(drop=False)
df2.columns = ["模型","MAE"]
df2["類別"] = "同地同時"
df2["裝置"] = df2["模型"].str.split("_")
df2["裝置"] = df2["裝置"].str[0]
df2

                模型         MAE    類別  裝置
0   01_weather.pkl  592.637267  同地同時  01
1   02_weather.pkl  689.106962  同地同時  02
2   03_weather.pkl  752.435121  同地同時  03
3   04_weather.pkl  627.351385  同地同時  04
4   05_weather.pkl  776.090069  同地同時  05
5   06_weather.pkl  854.395427  同地同時  06
6   07_weather.pkl  810.592500  同地同時  07
7   08_weather.pkl  497.546578  同地同時  08
8   09_weather.pkl  517.314217  同地同時  09
9   10_weather.pkl  609.078821  同地同時  10
10  11_weather.pkl  273.717240  同地同時  11
11  12_weather.pkl  508.576723  同地同時  12
12  13_weather.pkl  539.834000  同地同時  13
13  14_weather.pkl  668.127034  同地同時  14
14  15_weather.pkl  636.504518  同地同時  15
15  16_weather.pkl  568.146092  同地同時  16
16  17_weather.pkl  513.277668  同地同時  17

In [66]:
model_folder_name = "train_lastday_gridsearch_usealldata"  
with open(f"./model_each_location/{model_folder_name}/d_lastday.json", "r", encoding="utf-8") as file:
    mae_data = json.load(file)

In [67]:
df3 = pd.json_normalize(mae_data).transpose().reset_index(drop=False)
df3.columns = ["模型","MAE"]
df3["類別"] = "同地異時"
df3["裝置"] = df3["模型"].str.split(".")
df3["裝置"] = df3["裝置"].str[0]
df3

        模型          MAE    類別  裝置
0   01.pkl   792.459031  同地異時  01
1   02.pkl   952.229202  同地異時  02
2   03.pkl  1050.904783  同地異時  03
3   04.pkl   748.602963  同地異時  04
4   05.pkl   968.464031  同地異時  05
5   06.pkl   985.646988  同地異時  06
6   07.pkl   879.400068  同地異時  07
7   08.pkl   614.568539  同地異時  08
8   09.pkl   500.744996  同地異時  09
9   10.pkl   725.985634  同地異時  10
10  11.pkl   272.536655  同地異時  11
11  12.pkl   560.847897  同地異時  12
12  13.pkl   693.584246  同地異時  13
13  14.pkl   849.272908  同地異時  14
14  15.pkl   798.871033  同地異時  15
15  16.pkl   646.828425  同地異時  16
16  17.pkl   698.914940  同地異時  17

In [68]:
df = pd.concat([df1,df2,df3],axis=0)
df.to_csv("modelmae.csv",index=False)